[2024-07-22T02:34:57.488+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: example_dynamic_task_mapping.add_one scheduled__2022-10-30T00:00:00+00:00 map_index=0 [queued]>
[2024-07-22T02:34:57.526+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: example_dynamic_task_mapping.add_one scheduled__2022-10-30T00:00:00+00:00 map_index=0 [queued]>
[2024-07-22T02:34:57.532+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-07-22T02:34:57.557+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-07-22T02:34:57.570+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-07-22T02:34:57.669+0000] {taskinstance.py:1300} INFO - Executing <Mapped(_PythonDecoratedOperator): add_one> on 2022-10-30 00:00:00+00:00
[2024-07-22T02:34:57.706+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'example_dynamic_task_mapping', 'add_one', 'scheduled__2022-10-30T00:00:00+00:00', '--job-id', '988', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_dynamic_task_mapping.py', '--cfg-path', '/tmp/tmpolrc4pj9', '--map-index', '0']
[2024-07-22T02:34:57.709+0000] {standard_task_runner.py:83} INFO - Job 988: Subtask add_one
[2024-07-22T02:34:57.686+0000] {standard_task_runner.py:55} INFO - Started process 2775 to run task
[2024-07-22T02:34:57.891+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 988 for task add_one ([Errno 2] No such file or directory: '/opt/airflow/logs/dag_id=example_dynamic_task_mapping/run_id=scheduled__2022-10-30T00:00:00+00:00/task_id=add_one/map_index=0/attempt=1.log'; 2775)
[2024-07-22T02:34:57.903+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-07-22T02:34:57.950+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
