[2024-07-26T02:37:25.325+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_email_operator.4-Bash manual__2024-07-26T02:37:19.788881+00:00 [queued]>
[2024-07-26T02:37:25.332+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_email_operator.4-Bash manual__2024-07-26T02:37:19.788881+00:00 [queued]>
[2024-07-26T02:37:25.332+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-07-26T02:37:25.332+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-07-26T02:37:25.332+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-07-26T02:37:25.341+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): 4-Bash> on 2024-07-26 02:37:19.788881+00:00
[2024-07-26T02:37:25.343+0000] {standard_task_runner.py:55} INFO - Started process 1796 to run task
[2024-07-26T02:37:25.345+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exemplo_email_operator', '4-Bash', 'manual__2024-07-26T02:37:19.788881+00:00', '--job-id', '1470', '--raw', '--subdir', 'DAGS_FOLDER/exemplo_email_operator.py', '--cfg-path', '/tmp/tmpqa47tao2']
[2024-07-26T02:37:25.346+0000] {standard_task_runner.py:83} INFO - Job 1470: Subtask 4-Bash
[2024-07-26T02:37:25.381+0000] {task_command.py:388} INFO - Running <TaskInstance: exemplo_email_operator.4-Bash manual__2024-07-26T02:37:19.788881+00:00 [running]> on host 4e9420b3fb00
[2024-07-26T02:37:25.427+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caue.ausec@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exemplo_email_operator
AIRFLOW_CTX_TASK_ID=4-Bash
AIRFLOW_CTX_EXECUTION_DATE=2024-07-26T02:37:19.788881+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-26T02:37:19.788881+00:00
[2024-07-26T02:37:25.428+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-26T02:37:25.429+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-07-26T02:37:25.436+0000] {subprocess.py:86} INFO - Output:
[2024-07-26T02:37:25.437+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-26T02:37:25.445+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-26T02:37:25.447+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=exemplo_email_operator, task_id=4-Bash, execution_date=20240726T023719, start_date=20240726T023725, end_date=20240726T023725
[2024-07-26T02:37:25.458+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1470 for task 4-Bash (Bash command failed. The command returned a non-zero exit code 1.; 1796)
[2024-07-26T02:37:25.483+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-07-26T02:37:25.504+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
