[2024-07-25T02:16:18.847+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_dag_complexa.tsk6 manual__2024-07-25T02:15:53.036872+00:00 [queued]>
[2024-07-25T02:16:18.864+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: exemplo_dag_complexa.tsk6 manual__2024-07-25T02:15:53.036872+00:00 [queued]>
[2024-07-25T02:16:18.870+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-07-25T02:16:18.875+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-07-25T02:16:18.877+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-07-25T02:16:18.915+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk6> on 2024-07-25 02:15:53.036872+00:00
[2024-07-25T02:16:18.926+0000] {standard_task_runner.py:55} INFO - Started process 31156 to run task
[2024-07-25T02:16:18.936+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exemplo_dag_complexa', 'tsk6', 'manual__2024-07-25T02:15:53.036872+00:00', '--job-id', '1378', '--raw', '--subdir', 'DAGS_FOLDER/exemplo_dag_complexa.py', '--cfg-path', '/tmp/tmpcesugp3i']
[2024-07-25T02:16:18.940+0000] {standard_task_runner.py:83} INFO - Job 1378: Subtask tsk6
[2024-07-25T02:16:19.112+0000] {task_command.py:388} INFO - Running <TaskInstance: exemplo_dag_complexa.tsk6 manual__2024-07-25T02:15:53.036872+00:00 [running]> on host 448a9c84d52e
[2024-07-25T02:16:19.169+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exemplo_dag_complexa
AIRFLOW_CTX_TASK_ID=tsk6
AIRFLOW_CTX_EXECUTION_DATE=2024-07-25T02:15:53.036872+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-25T02:15:53.036872+00:00
[2024-07-25T02:16:19.171+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-25T02:16:19.173+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-07-25T02:16:19.184+0000] {subprocess.py:86} INFO - Output:
[2024-07-25T02:16:19.185+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-25T02:16:19.200+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-25T02:16:19.210+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=exemplo_dag_complexa, task_id=tsk6, execution_date=20240725T021553, start_date=20240725T021618, end_date=20240725T021619
[2024-07-25T02:16:19.229+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1378 for task tsk6 (Bash command failed. The command returned a non-zero exit code 1.; 31156)
[2024-07-25T02:16:19.243+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-07-25T02:16:19.265+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
